/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PathFindingVisualizer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new PathFindingVisualizerGUI();
        // PathFindingVisualizerGUI gui = new PathFindingVisualizerGUI();
    }
}
