/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PathFindingVisualizer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        PathFindingVisualizerGUI gui = new PathFindingVisualizerGUI();
    }
}
